import DashboardLayout from "../components/DashboardLayout";

export default function ReportsPage() {

    const reports = [

        {
            title: "Daily Report",
            team: "TikTok",
            created: "Today",
            status: "Completed",
        },

        {
            title: "Video Production",
            team: "Video",
            created: "Today",
            status: "Completed",
        },

        {
            title: "Developer Report",
            team: "Developer",
            created: "Today",
            status: "Running",
        },

        {
            title: "Research Report",
            team: "Research",
            created: "Today",
            status: "Completed",
        },

        {
            title: "Website Report",
            team: "Website",
            created: "Today",
            status: "Completed",
        }

    ];

    return (

        <DashboardLayout>

            <div className="space-y-8">

                <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8">

                    <h1 className="text-3xl font-bold text-white">

                        Reports Center

                    </h1>

                    <p className="text-zinc-400 mt-2">

                        Reports generated by every AI team.

                    </p>

                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

                    {reports.map((report) => (

                        <div
                            key={report.title}
                            className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6"
                        >

                            <h2 className="text-xl font-bold text-white">

                                {report.title}

                            </h2>

                            <div className="mt-5 space-y-2">

                                <p className="text-zinc-400">

                                    Team:
                                    <span className="text-white ml-2">
                                        {report.team}
                                    </span>

                                </p>

                                <p className="text-zinc-400">

                                    Created:
                                    <span className="text-white ml-2">
                                        {report.created}
                                    </span>

                                </p>

                                <p className="text-zinc-400">

                                    Status:
                                    <span className="text-green-400 ml-2">
                                        {report.status}
                                    </span>

                                </p>

                            </div>

                            <div className="mt-6 flex gap-3">

                                <button className="px-4 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-500">

                                    View

                                </button>

                                <button className="px-4 py-2 rounded-lg bg-green-600 hover:bg-green-500">

                                    Download

                                </button>

                                <button className="px-4 py-2 rounded-lg bg-zinc-700 hover:bg-zinc-600">

                                    Share

                                </button>

                            </div>

                        </div>

                    ))}

                </div>

            </div>

        </DashboardLayout>

    );

}
